title: mikam.info
description: A jack of all trades is a master of none, but oftentimes better than a master of one.
author: mikam

theme: minima

show_excerpts: true

header_pages:
  - _pages/frontpage.md
  - _pages/about.md
  - _pages/archive.md

include:
    - _pages
